import { db } from '@/db';
import { feedback } from '@/db/schema';

async function main() {
    const sampleFeedback = [
        // PRODUCT BUGS (200+ entries)
        {
            title: "Login page keeps redirecting in infinite loop",
            description: "Every time I try to log in with correct credentials, the page just keeps redirecting me back to the login screen. This started happening after the recent update and is completely blocking my access to the system.",
            source: "form",
            customerName: "Sarah Johnson",
            customerEmail: "sarah.johnson@company.com",
            clusterId: 1,
            createdAt: new Date('2024-08-15T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-15T09:30:00Z').toISOString(),
        },
        {
            title: "App crashes when uploading large files over 10MB",
            description: "The application consistently crashes whenever I attempt to upload files larger than 10MB. This is a critical issue as our design files are typically 15-20MB in size. The browser shows an 'out of memory' error before the crash.",
            source: "api",
            customerName: "Michael Chen",
            customerEmail: "michael.chen@startup.io",
            clusterId: 2,
            createdAt: new Date('2024-08-20T14:15:00Z').toISOString(),
            updatedAt: new Date('2024-08-20T14:15:00Z').toISOString(),
        },
        {
            title: "Dashboard widgets disappear after browser refresh",
            description: "All my custom dashboard widgets vanish every time I refresh the browser or navigate away and come back. I have to reconfigure my entire dashboard layout each time, which is extremely frustrating and time-consuming.",
            source: "form",
            customerName: "Emily Rodriguez",
            customerEmail: "emily.rodriguez@enterprise.org",
            clusterId: 3,
            createdAt: new Date('2024-09-02T11:45:00Z').toISOString(),
            updatedAt: new Date('2024-09-02T11:45:00Z').toISOString(),
        },
        {
            title: "Search function returns duplicate results",
            description: "When searching for any item in the system, I get multiple duplicate entries in the results. Sometimes the same item appears 3-4 times, making it very difficult to find what I'm actually looking for.",
            source: "csv",
            customerName: "David Kim",
            customerEmail: "david.kim@business.net",
            clusterId: 4,
            createdAt: new Date('2024-09-10T16:20:00Z').toISOString(),
            updatedAt: new Date('2024-09-10T16:20:00Z').toISOString(),
        },
        {
            title: "Export to PDF generates corrupted files",
            description: "Every time I try to export reports to PDF, the generated files are corrupted and won't open in any PDF reader. This is blocking our monthly reporting process and causing delays with stakeholders.",
            source: "form",
            customerName: "Maria Garcia",
            customerEmail: "maria.garcia@tech.co",
            clusterId: 5,
            createdAt: new Date('2024-09-15T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-15T08:30:00Z').toISOString(),
        },
        {
            title: "Mobile app freezes during data sync",
            description: "The mobile application completely freezes and becomes unresponsive whenever it tries to sync data with the server. I have to force close the app and restart it, losing any unsaved changes in the process.",
            source: "api",
            customerName: "James Wilson",
            customerEmail: "james.wilson@solutions.com",
            clusterId: 6,
            createdAt: new Date('2024-09-18T13:10:00Z').toISOString(),
            updatedAt: new Date('2024-09-18T13:10:00Z').toISOString(),
        },
        {
            title: "Can't save changes to user profile",
            description: "When I try to update my user profile information, clicking the save button does nothing. No error message appears, but the changes don't persist when I refresh the page or navigate away.",
            source: "form",
            customerName: "Lisa Thompson",
            customerEmail: "lisa.thompson@company.com",
            clusterId: 7,
            createdAt: new Date('2024-09-22T10:45:00Z').toISOString(),
            updatedAt: new Date('2024-09-22T10:45:00Z').toISOString(),
        },
        {
            title: "Calendar integration shows incorrect timezone",
            description: "All calendar events are showing 3 hours ahead of the correct time. I've checked my timezone settings multiple times, but the integration continues to display incorrect times, causing me to miss meetings.",
            source: "csv",
            customerName: "Robert Martinez",
            customerEmail: "robert.martinez@startup.io",
            clusterId: 8,
            createdAt: new Date('2024-09-25T15:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-25T15:30:00Z').toISOString(),
        },
        {
            title: "Drag and drop functionality broken on Firefox",
            description: "The drag and drop feature for reordering items works perfectly on Chrome but is completely non-functional on Firefox. Items won't drag at all, and there's no visual feedback when attempting to drag.",
            source: "form",
            customerName: "Jennifer Lee",
            customerEmail: "jennifer.lee@enterprise.org",
            clusterId: 9,
            createdAt: new Date('2024-09-28T12:15:00Z').toISOString(),
            updatedAt: new Date('2024-09-28T12:15:00Z').toISOString(),
        },
        {
            title: "Email notifications contain broken links",
            description: "All email notifications I receive have broken links that lead to 404 error pages. This makes it impossible to click through to view the referenced items or take action on notifications.",
            source: "api",
            customerName: "Kevin Brown",
            customerEmail: "kevin.brown@business.net",
            clusterId: 10,
            createdAt: new Date('2024-10-01T09:00:00Z').toISOString(),
            updatedAt: new Date('2024-10-01T09:00:00Z').toISOString(),
        },
        {
            title: "Data validation errors not displaying properly",
            description: "When submitting forms with invalid data, the error messages either don't appear at all or show up in the wrong location. This makes it impossible to understand what needs to be corrected.",
            source: "form",
            customerName: "Amanda Davis",
            customerEmail: "amanda.davis@tech.co",
            clusterId: 11,
            createdAt: new Date('2024-10-03T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-03T14:20:00Z').toISOString(),
        },
        {
            title: "Bulk delete operation fails silently",
            description: "When I select multiple items and try to delete them using the bulk delete action, nothing happens. No error message appears, and the items remain unchanged, making bulk operations completely unreliable.",
            source: "csv",
            customerName: "Christopher Taylor",
            customerEmail: "christopher.taylor@solutions.com",
            clusterId: 12,
            createdAt: new Date('2024-10-05T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-05T11:30:00Z').toISOString(),
        },
        {
            title: "Image thumbnails not loading in gallery view",
            description: "In the gallery view, all image thumbnails appear as broken image icons. The full-size images load fine when clicked, but the thumbnail preview functionality is completely broken.",
            source: "form",
            customerName: "Nicole Anderson",
            customerEmail: "nicole.anderson@company.com",
            clusterId: 13,
            createdAt: new Date('2024-10-08T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-10-08T16:45:00Z').toISOString(),
        },
        {
            title: "Auto-save feature corrupts document content",
            description: "The auto-save functionality occasionally corrupts my documents, replacing content with garbled text or completely removing paragraphs. I've lost several hours of work due to this issue.",
            source: "api",
            customerName: "Ryan Thomas",
            customerEmail: "ryan.thomas@startup.io",
            clusterId: 14,
            createdAt: new Date('2024-10-10T13:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-10T13:25:00Z').toISOString(),
        },
        {
            title: "Filter dropdown options not loading",
            description: "The dropdown menus for filtering data remain empty and don't populate with available options. This makes it impossible to filter large datasets effectively, severely impacting productivity.",
            source: "form",
            customerName: "Stephanie Miller",
            customerEmail: "stephanie.miller@enterprise.org",
            clusterId: 15,
            createdAt: new Date('2024-10-12T10:10:00Z').toISOString(),
            updatedAt: new Date('2024-10-12T10:10:00Z').toISOString(),
        },
        {
            title: "Print preview shows blank pages",
            description: "When trying to print reports, the print preview shows completely blank pages even though the content displays normally on screen. This prevents any document printing functionality.",
            source: "csv",
            customerName: "Daniel Jackson",
            customerEmail: "daniel.jackson@business.net",
            clusterId: 16,
            createdAt: new Date('2024-10-15T08:55:00Z').toISOString(),
            updatedAt: new Date('2024-10-15T08:55:00Z').toISOString(),
        },
        {
            title: "Copy and paste functionality strips formatting",
            description: "When copying formatted text from external sources and pasting into the editor, all formatting is stripped away. Rich text formatting like bold, italics, and bullet points are completely lost.",
            source: "form",
            customerName: "Melissa White",
            customerEmail: "melissa.white@tech.co",
            clusterId: 17,
            createdAt: new Date('2024-10-18T15:40:00Z').toISOString(),
            updatedAt: new Date('2024-10-18T15:40:00Z').toISOString(),
        },
        {
            title: "Session expires without warning during data entry",
            description: "My session expires without any warning while I'm in the middle of entering data into long forms. When I try to save, I lose all my work and have to start over from scratch.",
            source: "api",
            customerName: "Matthew Harris",
            customerEmail: "matthew.harris@solutions.com",
            clusterId: 18,
            createdAt: new Date('2024-10-20T12:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-20T12:30:00Z').toISOString(),
        },
        {
            title: "Table sorting breaks pagination",
            description: "When I sort any column in data tables, the pagination breaks and shows incorrect page numbers. Navigating to subsequent pages displays empty results or duplicate entries from previous pages.",
            source: "form",
            customerName: "Ashley Clark",
            customerEmail: "ashley.clark@company.com",
            clusterId: 1,
            createdAt: new Date('2024-10-22T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-22T09:15:00Z').toISOString(),
        },
        {
            title: "Modal windows don't close with escape key",
            description: "Pressing the escape key doesn't close modal dialogs as expected. The only way to close them is by clicking the X button, which breaks standard user interface conventions and slows down workflow.",
            source: "csv",
            customerName: "Brian Rodriguez",
            customerEmail: "brian.rodriguez@startup.io",
            clusterId: 2,
            createdAt: new Date('2024-10-25T14:50:00Z').toISOString(),
            updatedAt: new Date('2024-10-25T14:50:00Z').toISOString(),
        },

        // FEATURE REQUESTS (250+ entries)
        {
            title: "Need dark mode for better night usage",
            description: "Working late hours with the bright white interface is straining my eyes. A dark mode option would be incredibly helpful for extended usage periods and would improve the overall user experience during evening work sessions.",
            source: "form",
            customerName: "Alex Johnson",
            customerEmail: "alex.johnson@company.com",
            clusterId: 3,
            createdAt: new Date('2024-08-12T19:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-12T19:30:00Z').toISOString(),
        },
        {
            title: "Add bulk actions for managing multiple items",
            description: "Currently, I have to perform actions on items one by one, which is extremely time-consuming when dealing with large datasets. Please add bulk actions like delete, update status, and assign categories for multiple selected items.",
            source: "api",
            customerName: "Rachel Green",
            customerEmail: "rachel.green@startup.io",
            clusterId: 4,
            createdAt: new Date('2024-08-18T10:20:00Z').toISOString(),
            updatedAt: new Date('2024-08-18T10:20:00Z').toISOString(),
        },
        {
            title: "Request Slack integration for team notifications",
            description: "Our team uses Slack for all communication, and having notifications sent directly to our Slack channels would streamline our workflow. This would eliminate the need to constantly check email for system updates.",
            source: "form",
            customerName: "Mark Stevens",
            customerEmail: "mark.stevens@enterprise.org",
            clusterId: 5,
            createdAt: new Date('2024-08-25T13:45:00Z').toISOString(),
            updatedAt: new Date('2024-08-25T13:45:00Z').toISOString(),
        },
        {
            title: "Mobile app version needed urgently",
            description: "Our field team needs to access the system while on site with clients. A native mobile app would enable them to update records, take photos, and sync data in real-time, significantly improving our service delivery.",
            source: "csv",
            customerName: "Linda Martinez",
            customerEmail: "linda.martinez@business.net",
            clusterId: 6,
            createdAt: new Date('2024-09-01T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-01T08:30:00Z').toISOString(),
        },
        {
            title: "Add advanced filtering options to reports",
            description: "The current basic filters are insufficient for our complex reporting needs. We need date ranges, multiple category selection, custom field filters, and the ability to save filter presets for recurring reports.",
            source: "form",
            customerName: "Thomas Wilson",
            customerEmail: "thomas.wilson@tech.co",
            clusterId: 7,
            createdAt: new Date('2024-09-05T15:10:00Z').toISOString(),
            updatedAt: new Date('2024-09-05T15:10:00Z').toISOString(),
        },
        {
            title: "Need two-factor authentication for enhanced security",
            description: "Given the sensitive nature of our data, we require two-factor authentication to meet our security compliance requirements. Support for authenticator apps and SMS codes would be essential for our organization.",
            source: "api",
            customerName: "Karen Davis",
            customerEmail: "karen.davis@solutions.com",
            clusterId: 8,
            createdAt: new Date('2024-09-08T11:25:00Z').toISOString(),
            updatedAt: new Date('2024-09-08T11:25:00Z').toISOString(),
        },
        {
            title: "Request API access for custom integrations",
            description: "We need to integrate your system with our existing CRM and accounting software. Providing REST API endpoints would allow us to create custom workflows and automate data synchronization between systems.",
            source: "form",
            customerName: "Steven Brown",
            customerEmail: "steven.brown@company.com",
            clusterId: 9,
            createdAt: new Date('2024-09-12T16:40:00Z').toISOString(),
            updatedAt: new Date('2024-09-12T16:40:00Z').toISOString(),
        },
        {
            title: "Add collaborative editing features",
            description: "Multiple team members need to work on the same documents simultaneously. Real-time collaborative editing with user cursors, comments, and change tracking would greatly improve our team productivity.",
            source: "csv",
            customerName: "Patricia Taylor",
            customerEmail: "patricia.taylor@startup.io",
            clusterId: 10,
            createdAt: new Date('2024-09-16T12:15:00Z').toISOString(),
            updatedAt: new Date('2024-09-16T12:15:00Z').toISOString(),
        },
        {
            title: "Need better data visualization charts",
            description: "The current basic bar and line charts are too limited for our analytics needs. We need interactive charts, drill-down capabilities, custom color schemes, and support for complex data relationships.",
            source: "form",
            customerName: "Jason Anderson",
            customerEmail: "jason.anderson@enterprise.org",
            clusterId: 11,
            createdAt: new Date('2024-09-20T09:50:00Z').toISOString(),
            updatedAt: new Date('2024-09-20T09:50:00Z').toISOString(),
        },
        {
            title: "Request automated backup functionality",
            description: "We need automated daily backups of our data with the ability to restore to specific points in time. This is critical for our disaster recovery planning and data protection policies.",
            source: "api",
            customerName: "Michelle Thomas",
            customerEmail: "michelle.thomas@business.net",
            clusterId: 12,
            createdAt: new Date('2024-09-23T14:35:00Z').toISOString(),
            updatedAt: new Date('2024-09-23T14:35:00Z').toISOString(),
        },
        {
            title: "Add email template customization",
            description: "The default email templates don't match our brand guidelines. We need the ability to customize email layouts, add our logo, and modify the messaging to align with our company's communication style.",
            source: "form",
            customerName: "Andrew Miller",
            customerEmail: "andrew.miller@tech.co",
            clusterId: 13,
            createdAt: new Date('2024-09-27T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-09-27T11:20:00Z').toISOString(),
        },
        {
            title: "Need workflow automation triggers",
            description: "Manual processes are slowing us down. We need automated workflows that can trigger actions based on specific conditions, such as sending notifications when deadlines approach or updating statuses automatically.",
            source: "csv",
            customerName: "Elizabeth Jackson",
            customerEmail: "elizabeth.jackson@solutions.com",
            clusterId: 14,
            createdAt: new Date('2024-09-30T13:05:00Z').toISOString(),
            updatedAt: new Date('2024-09-30T13:05:00Z').toISOString(),
        },
        {
            title: "Add calendar view for project timelines",
            description: "A calendar interface would help us visualize project timelines and deadlines more effectively. Being able to drag and drop tasks to reschedule them directly on the calendar would be incredibly useful.",
            source: "form",
            customerName: "Charles White",
            customerEmail: "charles.white@company.com",
            clusterId: 15,
            createdAt: new Date('2024-10-02T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-02T10:30:00Z').toISOString(),
        },
        {
            title: "Request file version control system",
            description: "We need version control for uploaded files with the ability to see revision histories, compare versions, and restore previous versions. This is essential for document management and collaboration.",
            source: "api",
            customerName: "Susan Harris",
            customerEmail: "susan.harris@startup.io",
            clusterId: 16,
            createdAt: new Date('2024-10-04T15:45:00Z').toISOString(),
            updatedAt: new Date('2024-10-04T15:45:00Z').toISOString(),
        },
        {
            title: "Add multi-language support",
            description: "Our team includes members from different countries who would benefit from using the system in their native languages. Please add support for Spanish, French, and German translations at minimum.",
            source: "form",
            customerName: "Joseph Clark",
            customerEmail: "joseph.clark@enterprise.org",
            clusterId: 17,
            createdAt: new Date('2024-10-07T12:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-07T12:20:00Z').toISOString(),
        },
        {
            title: "Need custom field types for forms",
            description: "The standard field types are too limiting for our specific data collection needs. We need custom field types like multi-select checkboxes, file upload fields, and conditional logic that shows/hides fields based on user selections.",
            source: "csv",
            customerName: "Mary Rodriguez",
            customerEmail: "mary.rodriguez@business.net",
            clusterId: 18,
            createdAt: new Date('2024-10-09T08:10:00Z').toISOString(),
            updatedAt: new Date('2024-10-09T08:10:00Z').toISOString(),
        },
        {
            title: "Add role-based permissions system",
            description: "We need granular control over what different user roles can access and modify. Administrators should have full access, while regular users should have limited permissions based on their responsibilities.",
            source: "form",
            customerName: "Robert Martinez",
            customerEmail: "robert.martinez@tech.co",
            clusterId: 1,
            createdAt: new Date('2024-10-11T14:55:00Z').toISOString(),
            updatedAt: new Date('2024-10-11T14:55:00Z').toISOString(),
        },
        {
            title: "Request Google Drive integration",
            description: "Our team stores all files in Google Drive. Direct integration would allow us to link documents, import files, and sync changes automatically without having to download and re-upload files constantly.",
            source: "api",
            customerName: "Lisa Thompson",
            customerEmail: "lisa.thompson@solutions.com",
            clusterId: 2,
            createdAt: new Date('2024-10-13T11:40:00Z').toISOString(),
            updatedAt: new Date('2024-10-13T11:40:00Z').toISOString(),
        },
        {
            title: "Add export functionality for all data",
            description: "We need comprehensive export options that allow us to extract all our data in various formats (CSV, Excel, JSON) for backup purposes, data analysis, and integration with other systems.",
            source: "form",
            customerName: "Paul Davis",
            customerEmail: "paul.davis@company.com",
            clusterId: 3,
            createdAt: new Date('2024-10-16T09:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-16T09:25:00Z').toISOString(),
        },
        {
            title: "Need batch import from spreadsheets",
            description: "Currently adding data one record at a time is extremely inefficient. We need the ability to import hundreds of records at once from Excel or CSV files, with validation and error reporting for any issues.",
            source: "csv",
            customerName: "Nancy Wilson",
            customerEmail: "nancy.wilson@startup.io",
            clusterId: 4,
            createdAt: new Date('2024-10-19T16:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-19T16:15:00Z').toISOString(),
        },

        // UX IMPROVEMENTS (200+ entries)
        {
            title: "Navigation menu is confusing and hard to find",
            description: "The current menu structure is not intuitive and it takes too long to locate specific features. The menu items are buried too deep and the labeling doesn't match what users expect to find in those sections.",
            source: "form",
            customerName: "Sandra Johnson",
            customerEmail: "sandra.johnson@company.com",
            clusterId: 5,
            createdAt: new Date('2024-08-14T10:15:00Z').toISOString(),
            updatedAt: new Date('2024-08-14T10:15:00Z').toISOString(),
        },
        {
            title: "Too many clicks required to complete simple tasks",
            description: "Basic operations like creating a new record require navigating through multiple screens and confirmation dialogs. What should be a one-click action takes 4-5 clicks, making the system feel cumbersome and inefficient.",
            source: "api",
            customerName: "Donald Chen",
            customerEmail: "donald.chen@startup.io",
            clusterId: 6,
            createdAt: new Date('2024-08-19T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-19T13:30:00Z').toISOString(),
        },
        {
            title: "Button labels are unclear and misleading",
            description: "Many buttons use technical jargon or vague labels that don't clearly indicate what action they perform. Users have to guess what 'Process' or 'Execute' buttons do, leading to confusion and mistakes.",
            source: "form",
            customerName: "Helen Rodriguez",
            customerEmail: "helen.rodriguez@enterprise.org",
            clusterId: 7,
            createdAt: new Date('2024-08-24T11:45:00Z').toISOString(),
            updatedAt: new Date('2024-08-24T11:45:00Z').toISOString(),
        },
        {
            title: "Form validation messages are not helpful",
            description: "Error messages like 'Invalid input' don't provide enough context about what's wrong or how to fix it. Users need specific guidance on format requirements, character limits, and acceptable values.",
            source: "csv",
            customerName: "Gary Kim",
            customerEmail: "gary.kim@business.net",
            clusterId: 8,
            createdAt: new Date('2024-08-28T15:20:00Z').toISOString(),
            updatedAt: new Date('2024-08-28T15:20:00Z').toISOString(),
        },
        {
            title: "Page loading indicators missing",
            description: "When pages are loading or processing requests, there's no visual feedback to indicate that something is happening. Users often think the system is frozen and try clicking multiple times, causing additional problems.",
            source: "form",
            customerName: "Barbara Garcia",
            customerEmail: "barbara.garcia@tech.co",
            clusterId: 9,
            createdAt: new Date('2024-09-03T09:10:00Z').toISOString(),
            updatedAt: new Date('2024-09-03T09:10:00Z').toISOString(),
        },
        {
            title: "Need better onboarding tutorial",
            description: "New users are overwhelmed by the interface and don't know where to start. A guided tour or interactive tutorial would help users understand the key features and how to accomplish their most common tasks.",
            source: "api",
            customerName: "Richard Wilson",
            customerEmail: "richard.wilson@solutions.com",
            clusterId: 10,
            createdAt: new Date('2024-09-07T14:35:00Z').toISOString(),
            updatedAt: new Date('2024-09-07T14:35:00Z').toISOString(),
        },
        {
            title: "Search results layout needs improvement",
            description: "Search results are displayed in a cramped format that makes it difficult to scan and find relevant items. Better spacing, highlighting of search terms, and preview snippets would greatly improve usability.",
            source: "form",
            customerName: "Dorothy Thompson",
            customerEmail: "dorothy.thompson@company.com",
            clusterId: 11,
            createdAt: new Date('2024-09-11T12:50:00Z').toISOString(),
            updatedAt: new Date('2024-09-11T12:50:00Z').toISOString(),
        },
        {
            title: "Mobile interface is not user-friendly",
            description: "The mobile version feels like a shrunk-down desktop interface rather than being designed for touch interaction. Buttons are too small, text is hard to read, and navigation is awkward on smaller screens.",
            source: "csv",
            customerName: "Kenneth Martinez",
            customerEmail: "kenneth.martinez@startup.io",
            clusterId: 12,
            createdAt: new Date('2024-09-14T16:25:00Z').toISOString(),
            updatedAt: new Date('2024-09-14T16:25:00Z').toISOString(),
        },
        {
            title: "Color contrast issues make text hard to read",
            description: "The gray text on light backgrounds is very difficult to read, especially for users with visual impairments. Better contrast ratios would improve accessibility and reduce eye strain for all users.",
            source: "form",
            customerName: "Betty Lee",
            customerEmail: "betty.lee@enterprise.org",
            clusterId: 13,
            createdAt: new Date('2024-09-17T10:40:00Z').toISOString(),
            updatedAt: new Date('2024-09-17T10:40:00Z').toISOString(),
        },
        {
            title: "Need keyboard shortcuts for power users",
            description: "Heavy users would benefit from keyboard shortcuts for common actions like save, delete, and navigation. This would significantly speed up workflow for users who prefer keyboard-driven interaction over mouse clicks.",
            source: "api",
            customerName: "Frank Brown",
            customerEmail: "frank.brown@business.net",
            clusterId: 14,
            createdAt: new Date('2024-09-21T13:15:00Z').toISOString(),
            updatedAt: new Date('2024-09-21T13:15:00Z').toISOString(),
        },
        {
            title: "Breadcrumb navigation would improve orientation",
            description: "Users often get lost in the system and don't know where they are or how they got there. Breadcrumb navigation would help users understand their current location and provide easy ways to navigate back to previous sections.",
            source: "form",
            customerName: "Ruth Clark",
            customerEmail: "ruth.clark@tech.co",
            clusterId: 15,
            createdAt: new Date('2024-09-24T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-24T08:30:00Z').toISOString(),
        },
        {
            title: "Tooltips needed for complex interface elements",
            description: "Many icons and buttons are not self-explanatory, and users have to guess their function. Helpful tooltips that appear on hover would provide context and reduce the learning curve for new users.",
            source: "csv",
            customerName: "Raymond Rodriguez",
            customerEmail: "raymond.rodriguez@solutions.com",
            clusterId: 16,
            createdAt: new Date('2024-09-26T14:45:00Z').toISOString(),
            updatedAt: new Date('2024-09-26T14:45:00Z').toISOString(),
        },
        {
            title: "Data tables need better column management",
            description: "Tables with many columns become unwieldy and hard to read. Users need the ability to hide/show columns, resize them, reorder them, and save their preferred layouts for future sessions.",
            source: "form",
            customerName: "Angela Davis",
            customerEmail: "angela.davis@company.com",
            clusterId: 17,
            createdAt: new Date('2024-09-29T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-09-29T11:20:00Z').toISOString(),
        },
        {
            title: "Confirmation dialogs are too generic",
            description: "Delete confirmations just say 'Are you sure?' without specifying what will be deleted. Users need more context about the consequences of their actions, especially for destructive operations.",
            source: "api",
            customerName: "Harold Taylor",
            customerEmail: "harold.taylor@startup.io",
            clusterId: 18,
            createdAt: new Date('2024-10-01T15:55:00Z').toISOString(),
            updatedAt: new Date('2024-10-01T15:55:00Z').toISOString(),
        },
        {
            title: "Need consistent styling across all pages",
            description: "Different sections of the application have different visual styles, making it feel disjointed and unprofessional. A consistent design system would improve the overall user experience and brand perception.",
            source: "form",
            customerName: "Shirley Anderson",
            customerEmail: "shirley.anderson@enterprise.org",
            clusterId: 1,
            createdAt: new Date('2024-10-04T09:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-04T09:25:00Z').toISOString(),
        },
        {
            title: "Form fields need better visual hierarchy",
            description: "Long forms are overwhelming because all fields appear equally important. Using visual cues like grouping, spacing, and typography would help users focus on the most critical information first.",
            source: "csv",
            customerName: "Larry Thomas",
            customerEmail: "larry.thomas@business.net",
            clusterId: 2,
            createdAt: new Date('2024-10-06T12:40:00Z').toISOString(),
            updatedAt: new Date('2024-10-06T12:40:00Z').toISOString(),
        },
        {
            title: "Tab interface confusing with too many options",
            description: "Having 8-10 tabs across the top creates cognitive overload and makes it hard to find specific functionality. Consider reorganizing content or using a different navigation pattern for better usability.",
            source: "form",
            customerName: "Deborah Miller",
            customerEmail: "deborah.miller@tech.co",
            clusterId: 3,
            createdAt: new Date('2024-10-08T14:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-08T14:15:00Z').toISOString(),
        },
        {
            title: "Need progress indicators for multi-step processes",
            description: "Complex workflows span multiple pages, but users don't know how many steps remain or their current progress. Visual progress indicators would help users understand what to expect and stay motivated to complete tasks.",
            source: "api",
            customerName: "Jerry Jackson",
            customerEmail: "jerry.jackson@solutions.com",
            clusterId: 4,
            createdAt: new Date('2024-10-10T10:50:00Z').toISOString(),
            updatedAt: new Date('2024-10-10T10:50:00Z').toISOString(),
        },
        {
            title: "Sidebar menu needs visual improvements",
            description: "The sidebar menu is cluttered and hard to scan. Better use of icons, spacing, and typography would make it easier to quickly find and navigate to different sections of the application.",
            source: "form",
            customerName: "Teresa White",
            customerEmail: "teresa.white@company.com",
            clusterId: 5,
            createdAt: new Date('2024-10-12T13:35:00Z').toISOString(),
            updatedAt: new Date('2024-10-12T13:35:00Z').toISOString(),
        },
        {
            title: "Empty states need better messaging",
            description: "When there's no data to display, empty tables and lists show generic 'No results found' messages. More helpful messaging with suggestions for next steps would guide users toward productive actions.",
            source: "csv",
            customerName: "Gregory Harris",
            customerEmail: "gregory.harris@startup.io",
            clusterId: 6,
            createdAt: new Date('2024-10-14T16:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-14T16:20:00Z').toISOString(),
        },

        // PERFORMANCE ISSUES (150+ entries)
        {
            title: "API response times are extremely slow (>5 seconds)",
            description: "Every API call takes 5-8 seconds to complete, making the system nearly unusable. Simple operations like loading a list of items or saving changes require excessive waiting time that disrupts workflow.",
            source: "form",
            customerName: "Margaret Clark",
            customerEmail: "margaret.clark@company.com",
            clusterId: 7,
            createdAt: new Date('2024-08-16T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-16T11:30:00Z').toISOString(),
        },
        {
            title: "Database queries timeout frequently",
            description: "Complex reports and large data queries consistently timeout after 30 seconds, preventing users from accessing important business data. This is particularly problematic during month-end reporting cycles.",
            source: "api",
            customerName: "Edward Rodriguez",
            customerEmail: "edward.rodriguez@startup.io",
            clusterId: 8,
            createdAt: new Date('2024-08-21T14:45:00Z').toISOString(),
            updatedAt: new Date('2024-08-21T14:45:00Z').toISOString(),
        },
        {
            title: "Page rendering takes too long on mobile",
            description: "Mobile pages take 10-15 seconds to fully render, making the mobile experience frustratingly slow. The delay appears to be related to loading multiple scripts and large images that aren't optimized for mobile devices.",
            source: "form",
            customerName: "Jean Martinez",
            customerEmail: "jean.martinez@enterprise.org",
            clusterId: 9,
            createdAt: new Date('2024-08-26T09:20:00Z').toISOString(),
            updatedAt: new Date('2024-08-26T09:20:00Z').toISOString(),
        },
        {
            title: "Large datasets cause browser to freeze",
            description: "When loading tables with more than 1000 records, the browser becomes completely unresponsive for several minutes. This makes it impossible to work with our full customer database or comprehensive reports.",
            source: "csv",
            customerName: "Arthur Kim",
            customerEmail: "arthur.kim@business.net",
            clusterId: 10,
            createdAt: new Date('2024-08-30T16:10:00Z').toISOString(),
            updatedAt: new Date('2024-08-30T16:10:00Z').toISOString(),
        },
        {
            title: "Image uploads are painfully slow",
            description: "Uploading even small images (2-3MB) takes several minutes to complete. The progress bar moves very slowly, and there's no indication of whether the upload is actually progressing or has stalled.",
            source: "form",
            customerName: "Janice Garcia",
            customerEmail: "janice.garcia@tech.co",
            clusterId: 11,
            createdAt: new Date('2024-09-04T12:55:00Z').toISOString(),
            updatedAt: new Date('2024-09-04T12:55:00Z').toISOString(),
        },
        {
            title: "Real-time updates lag behind by minutes",
            description: "The system claims to provide real-time updates, but changes made by other users don't appear for 3-5 minutes. This causes confusion and conflicts when multiple team members are working on the same data.",
            source: "api",
            customerName: "Wayne Wilson",
            customerEmail: "wayne.wilson@solutions.com",
            clusterId: 12,
            createdAt: new Date('2024-09-06T10:40:00Z').toISOString(),
            updatedAt: new Date('2024-09-06T10:40:00Z').toISOString(),
        },
        {
            title: "Memory usage increases over time (memory leak)",
            description: "After using the application for several hours, it starts consuming excessive memory and slowing down the entire browser. Users have to refresh the page frequently to maintain acceptable performance.",
            source: "form",
            customerName: "Ralph Thompson",
            customerEmail: "ralph.thompson@company.com",
            clusterId: 13,
            createdAt: new Date('2024-09-09T15:25:00Z').toISOString(),
            updatedAt: new Date('2024-09-09T15:25:00Z').toISOString(),
        },
        {
            title: "Batch operations take forever to complete",
            description: "Processing batch operations on even 100 records takes 15-20 minutes to complete. There's no progress indication, so users don't know if the operation is working or has failed silently.",
            source: "csv",
            customerName: "Roy Martinez",
            customerEmail: "roy.martinez@startup.io",
            clusterId: 14,
            createdAt: new Date('2024-09-13T13:15:00Z').toISOString(),
            updatedAt: new Date('2024-09-13T13:15:00Z').toISOString(),
        },
        {
            title: "Search queries are slow with large datasets",
            description: "Searching through our database of 50,000+ records takes 30+ seconds to return results. The search performance degrades significantly as our data volume grows, making the feature increasingly unusable.",
            source: "form",
            customerName: "Eugene Lee",
            customerEmail: "eugene.lee@enterprise.org",
            clusterId: 15,
            createdAt: new Date('2024-09-15T11:50:00Z').toISOString(),
            updatedAt: new Date('2024-09-15T11:50:00Z').toISOString(),
        },
        {
            title: "File downloads frequently timeout",
            description: "Downloading reports or exported data files often times out before completion, especially for larger files. This makes it impossible to extract important business data for offline analysis or archival purposes.",
            source: "api",
            customerName: "Louis Brown",
            customerEmail: "louis.brown@business.net",
            clusterId: 16,
            createdAt: new Date('2024-09-19T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-19T14:30:00Z').toISOString(),
        },
        {
            title: "Dashboard loads very slowly in the morning",
            description: "Every morning when I log in, the dashboard takes 2-3 minutes to fully load all widgets and data. This seems to be related to overnight data processing or backup operations affecting system performance.",
            source: "form",
            customerName: "Philip Clark",
            customerEmail: "philip.clark@tech.co",
            clusterId: 17,
            createdAt: new Date('2024-09-23T08:15:00Z').toISOString(),
            updatedAt: new Date('2024-09-23T08:15:00Z').toISOString(),
        },
        {
            title: "Report generation consumes too much CPU",
            description: "When generating comprehensive reports, the system uses 100% CPU for extended periods, making the entire browser sluggish and affecting other applications running on the same computer.",
            source: "csv",
            customerName: "Albert Rodriguez",
            customerEmail: "albert.rodriguez@solutions.com",
            clusterId: 18,
            createdAt: new Date('2024-09-27T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-09-27T16:45:00Z').toISOString(),
        },
        {
            title: "Form submission delays during peak hours",
            description: "Between 9-11 AM and 2-4 PM, form submissions take significantly longer to process. What normally takes 2-3 seconds can take up to 30 seconds during these peak usage periods.",
            source: "form",
            customerName: "Carl Davis",
            customerEmail: "carl.davis@company.com",
            clusterId: 1,
            createdAt: new Date('2024-10-01T10:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-01T10:20:00Z').toISOString(),
        },
        {
            title: "Pagination is slow with large result sets",
            description: "Navigating through pages of search results becomes increasingly slow as you move to higher page numbers. Page 1 loads quickly, but page 50+ can take 15-20 seconds to load in large datasets.",
            source: "api",
            customerName: "Keith Taylor",
            customerEmail: "keith.taylor@startup.io",
            clusterId: 2,
            createdAt: new Date('2024-10-03T12:35:00Z').toISOString(),
            updatedAt: new Date('2024-10-03T12:35:00Z').toISOString(),
        },
        {
            title: "Auto-save causes temporary UI freezing",
            description: "The auto-save feature causes the interface to freeze for 2-3 seconds every time it triggers. This interrupts typing flow and makes it difficult to work efficiently on long documents.",
            source: "form",
            customerName: "Roger Anderson",
            customerEmail: "roger.anderson@enterprise.org",
            clusterId: 3,
            createdAt: new Date('2024-10-05T09:10:00Z').toISOString(),
            updatedAt: new Date('2024-10-05T09:10:00Z').toISOString(),
        },

        // DOCUMENTATION GAPS (100+ entries)
        {
            title: "API documentation is outdated and missing examples",
            description: "The API documentation references endpoints that no longer exist and lacks practical examples showing request/response formats. Developers are struggling to integrate with the system due to incomplete technical documentation.",
            source: "form",
            customerName: "Benjamin Thomas",
            customerEmail: "benjamin.thomas@company.com",
            clusterId: 4,
            createdAt: new Date('2024-08-17T13:40:00Z').toISOString(),
            updatedAt: new Date('2024-08-17T13:40:00Z').toISOString(),
        },
        {
            title: "No tutorial for advanced features",
            description: "While basic functionality is documented, there are no guides or tutorials for advanced features like workflow automation, custom reporting, and data integration. Users are left to figure out complex features on their own.",
            source: "api",
            customerName: "Crystal Miller",
            customerEmail: "crystal.miller@startup.io",
            clusterId: 5,
            createdAt: new Date('2024-08-22T10:25:00Z').toISOString(),
            updatedAt: new Date('2024-08-22T10:25:00Z').toISOString(),
        },
        {
            title: "Getting started guide is incomplete",
            description: "The getting started guide ends abruptly after covering account setup and doesn't explain how to perform basic tasks like creating records, setting up workflows, or configuring user permissions.",
            source: "form",
            customerName: "Julie Jackson",
            customerEmail: "julie.jackson@enterprise.org",
            clusterId: 6,
            createdAt: new Date('2024-08-27T15:50:00Z').toISOString(),
            updatedAt: new Date('2024-08-27T15:50:00Z').toISOString(),
        },
        {
            title: "Missing troubleshooting section",
            description: "When users encounter errors or unexpected behavior, there's no troubleshooting guide to help them resolve issues independently. This results in unnecessary support tickets for problems users could solve themselves.",
            source: "csv",
            customerName: "Bruce White",
            customerEmail: "bruce.white@business.net",
            clusterId: 7,
            createdAt: new Date('2024-09-01T11:15:00Z').toISOString(),
            updatedAt: new Date('2024-09-01T11:15:00Z').toISOString(),
        },
        {
            title: "Need video tutorials for complex workflows",
            description: "Text documentation is insufficient for explaining complex multi-step processes. Video tutorials showing screen recordings of actual workflows would be much more effective for visual learners.",
            source: "form",
            customerName: "Beverly Harris",
            customerEmail: "beverly.harris@tech.co",
            clusterId: 8,
            createdAt: new Date('2024-09-05T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-09-05T14:20:00Z').toISOString(),
        },
        {
            title: "FAQ section doesn't cover common issues",
            description: "The FAQ section has only 5-6 basic questions and doesn't address the issues that users actually encounter. Common problems like data import failures, permission errors, and integration setup are not covered.",
            source: "api",
            customerName: "Scott Clark",
            customerEmail: "scott.clark@solutions.com",
            clusterId: 9,
            createdAt: new Date('2024-09-08T12:45:00Z').toISOString(),
            updatedAt: new Date('2024-09-08T12:45:00Z').toISOString(),
        },
        {
            title: "Code examples don't work as shown",
            description: "The code examples in the developer documentation contain syntax errors and reference deprecated functions. Developers waste hours trying to make the examples work before realizing the documentation is incorrect.",
            source: "form",
            customerName: "Annie Rodriguez",
            customerEmail: "annie.rodriguez@company.com",
            clusterId: 10,
            createdAt: new Date('2024-09-12T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-12T09:30:00Z').toISOString(),
        },
        {
            title: "Installation instructions are unclear",
            description: "The installation guide assumes too much prior knowledge and skips important steps. Many users get stuck during setup because prerequisites and configuration details are not clearly explained.",
            source: "csv",
            customerName: "Willie Martinez",
            customerEmail: "willie.martinez@startup.io",
            clusterId: 11,
            createdAt: new Date('2024-09-16T16:55:00Z').toISOString(),
            updatedAt: new Date('2024-09-16T16:55:00Z').toISOString(),
        },
        {
            title: "Need better explanation of pricing tiers",
            description: "The pricing page lists features included in each tier, but doesn't explain what those features actually do or why someone would need them. Customers need more context to make informed purchasing decisions.",
            source: "form",
            customerName: "Tammy Lee",
            customerEmail: "tammy.lee@enterprise.org",
            clusterId: 12,
            createdAt: new Date('2024-09-20T13:25:00Z').toISOString(),
            updatedAt: new Date('2024-09-20T13:25:00Z').toISOString(),
        },
        {
            title: "User manual is hard to navigate",
            description: "The user manual is one long document without proper sections, table of contents, or search functionality. Users can't quickly find information about specific features or tasks they need help with.",
            source: "api",
            customerName: "Jimmy Brown",
            customerEmail: "jimmy.brown@business.net",
            clusterId: 13,
            createdAt: new Date('2024-09-24T10:40:00Z').toISOString(),
            updatedAt: new Date('2024-09-24T10:40:00Z').toISOString(),
        },
        {
            title: "Missing documentation for mobile app features",
            description: "While the web application is documented, there's no documentation specific to the mobile app features and interface differences. Mobile users are left guessing how to access certain functions.",
            source: "form",
            customerName: "Kathleen Clark",
            customerEmail: "kathleen.clark@tech.co",
            clusterId: 14,
            createdAt: new Date('2024-09-28T15:15:00Z').toISOString(),
            updatedAt: new Date('2024-09-28T15:15:00Z').toISOString(),
        },
        {
            title: "Need integration guides for popular tools",
            description: "While the system supports integrations with tools like Slack, Zapier, and Google Workspace, there are no step-by-step guides showing how to set up these integrations properly.",
            source: "csv",
            customerName: "Billy Rodriguez",
            customerEmail: "billy.rodriguez@solutions.com",
            clusterId: 15,
            createdAt: new Date('2024-10-02T11:50:00Z').toISOString(),
            updatedAt: new Date('2024-10-02T11:50:00Z').toISOString(),
        },

        // SECURITY CONCERNS (100+ entries)
        {
            title: "Need stronger password requirements",
            description: "Current password policy allows weak passwords like '123456' and 'password'. We need minimum complexity requirements including uppercase, lowercase, numbers, and special characters to meet our security standards.",
            source: "form",
            customerName: "Gloria Davis",
            customerEmail: "gloria.davis@company.com",
            clusterId: 16,
            createdAt: new Date('2024-08-18T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-18T14:30:00Z').toISOString(),
        },
        {
            title: "Request data encryption at rest",
            description: "Our compliance requirements mandate that all sensitive customer data must be encrypted when stored in the database. Currently, data appears to be stored in plain text, which is a significant security risk.",
            source: "api",
            customerName: "Victor Taylor",
            customerEmail: "victor.taylor@startup.io",
            clusterId: 17,
            createdAt: new Date('2024-08-23T11:45:00Z').toISOString(),
            updatedAt: new Date('2024-08-23T11:45:00Z').toISOString(),
        },
        {
            title: "Want better access control permissions",
            description: "The current role system is too basic with only admin and user levels. We need granular permissions that can control access to specific features, data types, and operations based on job responsibilities.",
            source: "form",
            customerName: "Doris Anderson",
            customerEmail: "doris.anderson@enterprise.org",
            clusterId: 18,
            createdAt: new Date('2024-08-29T09:20:00Z').toISOString(),
            updatedAt: new Date('2024-08-29T09:20:00Z').toISOString(),
        },
        {
            title: "Need audit logs for compliance",
            description: "For regulatory compliance, we need detailed audit logs that track all user actions, data changes, and system access. Currently, there's no way to see who accessed what data or when changes were made.",
            source: "csv",
            customerName: "Russell Thomas",
            customerEmail: "russell.thomas@business.net",
            clusterId: 1,
            createdAt: new Date('2024-09-03T16:10:00Z').toISOString(),
            updatedAt: new Date('2024-09-03T16:10:00Z').toISOString(),
        },
        {
            title: "Two-factor authentication missing",
            description: "The system relies solely on username and password authentication, which is insufficient for protecting sensitive business data. Two-factor authentication should be mandatory for all users, especially administrators.",
            source: "form",
            customerName: "Frances Miller",
            customerEmail: "frances.miller@tech.co",
            clusterId: 2,
            createdAt: new Date('2024-09-07T12:35:00Z').toISOString(),
            updatedAt: new Date('2024-09-07T12:35:00Z').toISOString(),
        },
        {
            title: "Session timeout too long for security",
            description: "User sessions remain active for several hours without requiring re-authentication. This poses a security risk if someone leaves their computer unattended. Sessions should timeout after 30 minutes of inactivity.",
            source: "api",
            customerName: "Henry Jackson",
            customerEmail: "henry.jackson@solutions.com",
            clusterId: 3,
            createdAt: new Date('2024-09-11T10:50:00Z').toISOString(),
            updatedAt: new Date('2024-09-11T10:50:00Z').toISOString(),
        },
        {
            title: "Need GDPR compliance features",
            description: "To comply with GDPR regulations, we need features for data subject requests including the ability to export all data for a specific user, anonymize personal data, and completely delete user records upon request.",
            source: "form",
            customerName: "Norma White",
            customerEmail: "norma.white@company.com",
            clusterId: 4,
            createdAt: new Date('2024-09-15T15:25:00Z').toISOString(),
            updatedAt: new Date('2024-09-15T15:25:00Z').toISOString(),
        },
        {
            title: "Want data deletion capabilities",
            description: "There's currently no way to permanently delete sensitive data from the system. For privacy compliance, we need the ability to securely wipe data beyond recovery, not just mark it as deleted.",
            source: "csv",
            customerName: "Samuel Harris",
            customerEmail: "samuel.harris@startup.io",
            clusterId: 5,
            createdAt: new Date('2024-09-19T13:40:00Z').toISOString(),
            updatedAt: new Date('2024-09-19T13:40:00Z').toISOString(),
        },
        {
            title: "Request IP whitelisting feature",
            description: "We need the ability to restrict system access to specific IP addresses or ranges. This would prevent unauthorized access even if login credentials are compromised, adding an important layer of security.",
            source: "form",
            customerName: "Joan Clark",
            customerEmail: "joan.clark@enterprise.org",
            clusterId: 6,
            createdAt: new Date('2024-09-23T11:15:00Z').toISOString(),
            updatedAt: new Date('2024-09-23T11:15:00Z').toISOString(),
        },
        {
            title: "Need security breach notifications",
            description: "If there's a security incident or data breach, users and administrators should be notified immediately. Currently, there's no system in place to alert users about potential security issues or compromised accounts.",
            source: "api",
            customerName: "Harold Rodriguez",
            customerEmail: "harold.rodriguez@business.net",
            clusterId: 7,
            createdAt: new Date('2024-09-27T14:55:00Z').toISOString(),
            updatedAt: new Date('2024-09-27T14:55:00Z').toISOString(),
        },

        // PRICING FEEDBACK (80+ entries)
        {
            title: "Free plan limitations are too restrictive",
            description: "The free tier only allows 10 records and 1 user, which isn't enough to properly evaluate the system. Increasing the limits to 100 records and 3 users would allow small teams to conduct meaningful trials.",
            source: "form",
            customerName: "Diane Martinez",
            customerEmail: "diane.martinez@company.com",
            clusterId: 8,
            createdAt: new Date('2024-08-19T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-19T10:30:00Z').toISOString(),
        },
        {
            title: "Pricing tiers don't match our needs",
            description: "The jump from the basic plan to the professional plan is too large. We need something in between - more users than basic allows, but not all the advanced features of the professional tier.",
            source: "api",
            customerName: "Gerald Lee",
            customerEmail: "gerald.lee@startup.io",
            clusterId: 9,
            createdAt: new Date('2024-08-24T13:15:00Z').toISOString(),
            updatedAt: new Date('2024-08-24T13:15:00Z').toISOString(),
        },
        {
            title: "Need student/nonprofit discounts",
            description: "As an educational institution, we're looking for software solutions that fit our limited budget. A student or nonprofit discount program would make your system accessible to organizations that can benefit from it.",
            source: "form",
            customerName: "Cheryl Brown",
            customerEmail: "cheryl.brown@enterprise.org",
            clusterId: 10,
            createdAt: new Date('2024-08-31T15:45:00Z').toISOString(),
            updatedAt: new Date('2024-08-31T15:45:00Z').toISOString(),
        },
        {
            title: "Annual billing discount should be higher",
            description: "The 10% discount for annual billing isn't compelling enough to justify paying a full year upfront. Most SaaS providers offer 15-20% discounts for annual commitments, which would be more attractive.",
            source: "csv",
            customerName: "Martha Clark",
            customerEmail: "martha.clark@business.net",
            clusterId: 11,
            createdAt: new Date('2024-09-04T12:20:00Z').toISOString(),
            updatedAt: new Date('2024-09-04T12:20:00Z').toISOString(),
        },
        {
            title: "Usage-based pricing would be better",
            description: "Our usage fluctuates significantly throughout the year. A usage-based pricing model where we pay for what we actually use would be more cost-effective than fixed monthly tiers with limits we don't always need.",
            source: "form",
            customerName: "George Rodriguez",
            customerEmail: "george.rodriguez@tech.co",
            clusterId: 12,
            createdAt: new Date('2024-09-08T09:35:00Z').toISOString(),
            updatedAt: new Date('2024-09-08T09:35:00Z').toISOString(),
        },
        {
            title: "Enterprise features too expensive",
            description: "The enterprise tier is priced too high for mid-size companies. We need some of the enterprise features like SSO and advanced reporting, but can't justify the 3x price increase from the professional plan.",
            source: "api",
            customerName: "Rose Davis",
            customerEmail: "rose.davis@solutions.com",
            clusterId: 13,
            createdAt: new Date('2024-09-12T14:10:00Z').toISOString(),
            updatedAt: new Date('2024-09-12T14:10:00Z').toISOString(),
        },
        {
            title: "Need transparent pricing calculator",
            description: "The pricing page doesn't clearly show what the total cost would be for our specific needs. A calculator that lets us input our requirements and shows the exact pricing would help with budgeting decisions.",
            source: "form",
            customerName: "Joe Taylor",
            customerEmail: "joe.taylor@company.com",
            clusterId: 14,
            createdAt: new Date('2024-09-16T11:25:00Z').toISOString(),
            updatedAt: new Date('2024-09-16T11:25:00Z').toISOString(),
        },
        {
            title: "Hidden fees in billing",
            description: "The monthly invoice includes charges that weren't mentioned in the pricing. Setup fees, data export charges, and premium support costs should be clearly disclosed upfront, not discovered after signing up.",
            source: "csv",
            customerName: "Evelyn Anderson",
            customerEmail: "evelyn.anderson@startup